### ISSUE TITLE
SCRIP format standards

### ISSUE THREAD

**Issue by hmb1** [SCRIP-Project/SCRIP#1]
Hi There,
I have some SCRIP NetCDF files to process and I am wondering what the standards are  with respect to  the polar regions and   wrapping ( grid cells that span the Greenwich meridian  or the Date line)

The SCRIP file I have has some  polar cells  that  are very wide in longitude (>100 degrees)  and very narrow  in latitude. ( < 0.5 degrees).  It also has some cells that cross the Greenwich meridian ( longitude goes from (   359.7505422628756833 -   0.2494577371223946 ).

I need an unambiguous way to differenciate   between these two cell types.  
Is this something that you have come across before ? 
Are wrapped cells even legal in SCRIP ?  
Any help greatly appreciated.
Thanks 

...Henry

**Comment by philipwjones** [comment]
@hmb1  - there are no "standards" per se.  SCRIP handles these internally and resets longitudes when necessary to make sure cell corners and intersections are handled consistently. Typically by shifting them as needed to the appropriate longitude interval based on a check that the longitude difference exceeds a certain range (I think 1.5pi so that we correctly treat cases with large ranges in longitude).

**Comment by hmb1** [comment]
@philipwjones 
thanks whats "1.5  pi" ?

**Comment by philipwjones** [comment]
@hmb1 SCRIP converts everything to radians internally, so it's 1.5 times the usual pi mathematical constant, corresponding to 3/4 of the total 2pi extent in radians over the globe
